Content-Type: multipart/mixed; boundary="------------nbD164W3u1Cck49B1k923iRn"
Message-ID: <949665dc-1807-4620-9d1d-09f7edaac913@gmail.com>
Date: Thu, 14 Dec 2023 15:54:26 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: nvxnah75@gmail.com
From: Xanh Nguyen <nvxanh75@gmail.com>
Subject: test 

This is a multi-part message in MIME format.
--------------nbD164W3u1Cck49B1k923iRn
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

test 14/12

--------------nbD164W3u1Cck49B1k923iRn
Content-Disposition: attachment; filename="Test mail server.docx""
Content-Transfer-Encoding: base64


--------------nbD164W3u1Cck49B1k923iRn