Content-Type: multipart/mixed; boundary="------------0K806JPgG50vTlx7D2Z1WjE3"
Message-ID: <275527cc-6665-4e95-84ca-adbf60854f9d@gmail.com>
Date: Thu, 14 Dec 2023 14:14:35 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: nvxanh75@gmail.com
From: Xanh Nguyen <nvxanh75@gmail.com>
Subject: test g???i file 

This is a multi-part message in MIME format.
--------------0K806JPgG50vTlx7D2Z1WjE3
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

test 14/12

--------------0K806JPgG50vTlx7D2Z1WjE3
Content-Disposition: attachment; filename="BTCN04 (1).docx""
Content-Transfer-Encoding: base64


--------------0K806JPgG50vTlx7D2Z1WjE3