Content-Type: multipart/mixed; boundary="------------726m5906gFD4949qYQv466z0"
Message-ID: <134839a4-39b0-4da1-bffc-ee6035b5a2e2@gmail.com>
Date: Thu, 14 Dec 2023 14:47:41 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: nvxanh75@gmail.com
From: Xanh Nguyen <nvxanh75@gmail.com>
Subject: test

This is a multi-part message in MIME format.
--------------726m5906gFD4949qYQv466z0
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

14/12

--------------726m5906gFD4949qYQv466z0
Content-Disposition: attachment; filename="Test mail server.docx""
Content-Transfer-Encoding: base64


--------------726m5906gFD4949qYQv466z0